process.env.JWT_ACCESS_SECRET = process.env.JWT_ACCESS_SECRET ?? 'test-secret-at-least-32-characters-long'
process.env.JWT_REFRESH_SECRET = process.env.JWT_REFRESH_SECRET ?? 'test-refresh-secret-at-least-32-chars'
process.env.LIVE_WEBHOOK_SECRET = process.env.LIVE_WEBHOOK_SECRET ?? 'test-live-webhook-secret-at-least-32-chars'
process.env.NODE_ENV = 'test'
process.env.DATABASE_URL = process.env.DATABASE_URL ?? 'postgresql://test:test@localhost:5432/test'
process.env.REDIS_URL = process.env.REDIS_URL ?? 'redis://127.0.0.1:6379'
