/**
 * Built-in admin panel views — the canonical view → endpoint map the web admin
 * ships with. `npm run seed:admin-views` upserts these into `admin_views`
 * (merging endpoints additively, never removing custom additions).
 *
 * Endpoint format: "METHOD /admin/path" — the path is relative to the
 * /api/{version} prefix and uses Fastify-style `:param` segments. Param NAMES
 * are irrelevant for matching (`:id` == `:userId`); see
 * `normalizeAdminEndpoint` in `adminView.service.ts`.
 */
export const DEFAULT_ADMIN_VIEWS: Record<string, string[]> = {
  LoginView: ['POST /admin/auth/login'],
  HomeView: [],
  AboutView: [],
  ReportsPlaceholderView: [],
  UserListView: ['GET /admin/users/search'],
  UserDetailView: [
    'GET /admin/users/search',
    'GET /admin/users/:id',
    'PATCH /admin/users/:id',
    'PUT /admin/users/:id/tags',
    'GET /admin/users/:id/wallet',
    'GET /admin/users/:id/devices',
    'GET /admin/users/:id/face-verification',
    'DELETE /admin/users/:id/face-verification',
    'GET /admin/users/transactions/filter-types',
    'GET /admin/users/:id/transactions/coins',
    'GET /admin/users/:id/transactions/points',
    'GET /admin/users/:id/transactions/trading-coins',
    'GET /admin/transactions/coins',
    'GET /admin/transactions/points',
    'GET /admin/transactions/trading-coins',
    'GET /admin/transactions/coin-trading-transfers',
    'GET /admin/transactions/gifts',
    'GET /admin/transactions/subscriptions',
    'GET /admin/transactions/vip-purchases',
    'GET /admin/transactions/store-purchases',
    'POST /admin/transactions/coins/:ledgerEntryId/revert',
    'POST /admin/transactions/points/:ledgerEntryId/revert',
    'POST /admin/transactions/coin-trading-transfers/:transferId/revert',
    'POST /admin/transactions/gifts/:giftTransactionId/revert',
    'POST /admin/users/:id/wallet/personal-coins/add',
    'POST /admin/users/:id/wallet/personal-coins/deduct',
    'POST /admin/users/:id/wallet/trading-coins/add',
    'POST /admin/users/:id/wallet/trading-coins/deduct',
    'POST /admin/users/:id/wallet/points/add',
    'POST /admin/users/:id/wallet/points/deduct',
    'POST /admin/users/:id/wallet/personal-coins/freeze',
    'POST /admin/users/:id/wallet/personal-coins/unfreeze',
    'POST /admin/users/:id/wallet/trading-coins/freeze',
    'POST /admin/users/:id/wallet/trading-coins/unfreeze',
    'POST /admin/users/:id/wallet/points/freeze',
    'POST /admin/users/:id/wallet/points/unfreeze',
    'GET /admin/posts',
    'GET /admin/posts/:postId',
    'DELETE /admin/posts/:postId',
    'POST /admin/posts/:postId/warn',
    'POST /admin/users/:id/posting/suspend',
    'POST /admin/users/:id/posting/ban',
    'POST /admin/users/:id/posting/activate',
    'POST /admin/users/:id/posting/restore',
    'POST /admin/users/:id/password/reset',
    'POST /admin/users/:id/profile/remove-avatar',
    'POST /admin/users/:id/profile/remove-bio',
    'POST /admin/users/:id/profile/reset-identity',
    'POST /admin/users/:id/agency/remove',
    'POST /admin/users/:id/devices/ban',
    'DELETE /admin/devices/:deviceId/ban',
  ],
  AgencyListView: [
    'GET /admin/agency/stats',
    'GET /admin/agency',
    'GET /admin/agency/applications/pending',
    'POST /admin/agency/:applicantUserId/approve',
    'POST /admin/agency/applications/:applicantUserId/reject',
  ],
  AgencyDetailView: [
    'GET /admin/agency/:identifier',
    'PATCH /admin/agency/:identifier/commission-tier',
    'POST /admin/agency/:identifier/hosts',
    'POST /admin/agency/:identifier/transfer-hosts',
    'POST /admin/agency/:identifier/suspend',
    'POST /admin/agency/:agencyUserId/unpause',
    'DELETE /admin/agency/:identifier',
    'POST /admin/users/:userId/messages/system',
  ],
  PlatformMessagesView: [
    'GET /admin/users/search',
    'POST /admin/users/:userId/messages/system',
    'POST /admin/users/:userId/messages/notification',
    'POST /admin/messages/notifications/broadcast',
  ],
  PushNotificationsView: [
    'GET /admin/notifications/push/users',
    'GET /admin/notifications/push/stats/today',
    'GET /admin/notifications/push/deliveries',
    'POST /admin/notifications/push/user/:userId',
    'POST /admin/notifications/push/broadcast',
    'GET /admin/users/search',
  ],
  LedgerAuditView: [
    'GET /admin/ledger-audit/flags',
    'PATCH /admin/ledger-audit/flags/:id',
    'POST /admin/ledger-audit/run',
    'GET /admin/users/search',
  ],
  GiftAdminView: [
    'GET /admin/gifts/analytics',
    'GET /admin/gifts',
    'POST /admin/gifts',
    'PATCH /admin/gifts/:giftId',
    'DELETE /admin/gifts/:giftId',
    'POST /admin/gifts/upload-url',
    'GET /admin/gift-categories',
    'POST /admin/gift-categories',
    'PATCH /admin/gift-categories/:categoryId',
    'GET /admin/gift-gallery/categories',
    'POST /admin/gift-gallery/categories',
    'PATCH /admin/gift-gallery/categories/:sectionId',
    'POST /admin/gift-gallery/categories/:sectionId/gifts',
    'DELETE /admin/gift-gallery/categories/:sectionId',
  ],
  StoreAdminView: [
    'GET /admin/store/analytics',
    'GET /admin/store/items',
    'POST /admin/store/items',
    'PATCH /admin/store/items/:id',
    'DELETE /admin/store/items/:id',
    'POST /admin/store/items/upload-url',
    'GET /admin/users/search',
    'GET /admin/users/:userId/store-items',
  ],
  TransactionsView: [
    'GET /admin/transactions/coins',
    'GET /admin/transactions/points',
    'GET /admin/transactions/trading-coins',
    'GET /admin/transactions/coin-trading-transfers',
    'GET /admin/transactions/gifts',
    'GET /admin/transactions/subscriptions',
    'GET /admin/transactions/vip-purchases',
    'GET /admin/transactions/store-purchases',
    'POST /admin/transactions/coins/:ledgerEntryId/revert',
    'POST /admin/transactions/points/:ledgerEntryId/revert',
    'POST /admin/transactions/coin-trading-transfers/:transferId/revert',
    'POST /admin/transactions/gifts/:giftTransactionId/revert',
    'GET /admin/users/search',
  ],
  BannerAdminView: [
    'GET /admin/banners',
    'POST /admin/banners',
    'PATCH /admin/banners/:bannerId',
    'DELETE /admin/banners/:bannerId',
    'POST /admin/banners/upload-url',
  ],
  CustomGiftAdminView: [
    'GET /admin/custom-gifts/config',
    'PUT /admin/custom-gifts/config',
    'GET /admin/custom-gifts/requests',
    'GET /admin/custom-gifts/requests/:requestId',
    'POST /admin/custom-gifts/requests/:requestId/complete',
    'POST /admin/custom-gifts/requests/:requestId/fail',
    'GET /admin/gifts',
  ],
  CustomerSupportView: [
    'GET /admin/support/csas/overview',
    'GET /admin/support/csas',
    'POST /admin/support/csas',
    'PATCH /admin/support/csas/:adminId',
    'PATCH /admin/support/csas/:adminId/status',
    'GET /admin/support/csas/export',
    'GET /admin/support/me/stats',
    'GET /admin/support/tickets',
    'GET /admin/support/tickets/:ticketId',
    'POST /admin/support/tickets/:ticketId/reply',
    'POST /admin/support/tickets/:ticketId/claim',
    'POST /admin/support/tickets/:ticketId/resolve',
    'POST /admin/support/tickets/:ticketId/close',
    'POST /admin/support/tickets/:ticketId/assign',
    'PATCH /admin/support/tickets/:ticketId/priority',
    'POST /admin/support/tickets/:ticketId/notes',
    'POST /admin/support/upload-url',
    'GET /admin/support/reports',
    'GET /admin/support/reports/:reportId',
    'PATCH /admin/support/reports/:reportId/status',
    'POST /admin/support/reports/:reportId/escalate',
  ],
  SupportTicketDetailView: [
    'GET /admin/support/tickets/:ticketId',
    'POST /admin/support/tickets/:ticketId/reply',
    'POST /admin/support/tickets/:ticketId/claim',
    'POST /admin/support/tickets/:ticketId/resolve',
    'POST /admin/support/tickets/:ticketId/close',
    'POST /admin/support/tickets/:ticketId/assign',
    'PATCH /admin/support/tickets/:ticketId/priority',
    'POST /admin/support/tickets/:ticketId/notes',
    'POST /admin/support/upload-url',
    'GET /admin/support/csas',
  ],
  OtpAuditLogsView: [
    'GET /admin/otp-delivery/audits',
    'GET /admin/otp-delivery/audits/summary',
    'GET /admin/otp-delivery/cost-rates',
    'GET /admin/otp-delivery/costs/monthly',
    'GET /admin/otp-delivery/costs/by-country',
  ],
}
